import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
const ROOT=process.cwd(), PORT=5213;
const vite=spawn(process.execPath,[ROOT+'/node_modules/vite/bin/vite.js','--host','127.0.0.1','--port',String(PORT),'--strictPort'],{cwd:ROOT,stdio:['ignore','pipe','pipe']});
await new Promise((r,j)=>{let o='';const h=d=>{o+=d;if(/ready in/.test(o))r()};vite.stdout.on('data',h);vite.stderr.on('data',h);setTimeout(()=>j(new Error('t/o')),40000)});
const b=await chromium.launch({headless:true,args:['--use-angle=default','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});
const p=await b.newPage({viewport:{width:800,height:600}});
p.on('pageerror',e=>console.log('PAGEERR:',e.message.split('\n')[0]));
await p.goto(`http://127.0.0.1:${PORT}/`,{waitUntil:'load',timeout:60000});
await p.waitForFunction(()=>window.__game?.ready,{timeout:180000});
await p.mouse.click(400,300);
await p.waitForTimeout(2200);
const r=await p.evaluate(async ()=>{
  const ctx=window.__game.ctx, M=ctx.musica;
  const esperar=(s)=>new Promise(r=>setTimeout(r,s*1000));
  const tocando=()=>Object.entries(M.faixas).filter(([,f])=>f.ok&&!f.el.paused&&f.gain.gain.value>0.05).map(([n])=>n);
  const out=[];
  const reg=(t)=>out.push(`${t.padEnd(22)} atual=${String(M.atual).padEnd(8)} audivel=[${tocando().join(',')}]`);
  reg('menu');
  ctx.state='jogando'; ctx.bus.emit('onda:inicio',{onda:1}); await esperar(2.2); reg('onda 1');
  const a1=M.acaoDaVez;
  ctx.bus.emit('onda:limpa',{onda:1}); await esperar(1.4); reg('setor limpo');
  ctx.bus.emit('onda:inicio',{onda:2}); await esperar(2.2); reg('onda 2');
  const a2=M.acaoDaVez;
  ctx.bus.emit('onda:limpa',{onda:2}); await esperar(1.4);
  ctx.bus.emit('onda:inicio',{onda:3}); await esperar(2.2); reg('onda 3');
  const a3=M.acaoDaVez;
  ctx.state='pausado'; M.update(); await esperar(2.6); reg('pausa');
  return {out, rodizio:[a1,a2,a3], est:M.estado()};
});
r.out.forEach(l=>console.log(l));
console.log('\nrodizio de acao nas ondas 1/2/3:', JSON.stringify(r.rodizio));
console.log('repetiu seguida?', r.rodizio[0]===r.rodizio[1] || r.rodizio[1]===r.rodizio[2] ? 'SIM (ruim)' : 'nao');
console.log('faixas carregadas:', JSON.stringify(r.est.carregadas));
await b.close(); vite.kill();
