import { spawn } from 'node:child_process';
import { chromium } from 'playwright';
const ROOT = process.cwd(), PORT = 5261;
const vite = spawn(process.execPath, [ROOT+'/node_modules/vite/bin/vite.js','--config','tools/vite.diag.config.js','--host','127.0.0.1','--port',String(PORT),'--strictPort'], {cwd:ROOT,stdio:['ignore','pipe','pipe']});
await new Promise((r,j)=>{const t=setTimeout(()=>j(new Error('t/o')),60000);vite.stdout.on('data',d=>{if(/ready in|Local:/i.test(String(d))){clearTimeout(t);r();}});});
const b = await chromium.launch({headless:true, executablePath:process.env.PW_CHROME||undefined, args:['--use-angle=default','--enable-unsafe-swiftshader','--ignore-gpu-blocklist','--mute-audio']});
const p = await b.newPage({viewport:{width:1280,height:720}});
const erros=[]; p.on('pageerror',e=>erros.push(String(e).split('\n')[0]));
p.on('console',m=>{if(m.type()==='error')erros.push('[console] '+m.text());});
await p.goto(`http://127.0.0.1:${PORT}/world.html`,{waitUntil:'load',timeout:120000});
await p.waitForFunction(()=>window.__pronto, undefined, {timeout:240000});
await p.evaluate(()=>window.__pausar());
await p.waitForTimeout(600);
await p.evaluate(()=>window.__pose([86,58,96],[-6,22,-14],46));
await p.waitForTimeout(400);
await p.screenshot({path:ROOT+'/shots/explorar-morro.png'});
const st = await p.evaluate(()=>window.__stats());
console.log('draw calls:', st.drawCalls, '| triangulos:', (st.triangulos/1000).toFixed(1)+'k', '| casas:', st.mundo.casas);
console.log('erros:', erros.length ? erros.slice(0,4) : 'nenhum');
await b.close(); vite.kill();
